// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Post = { id: string, title: string, subtitle: string | null, published: string, content: string, };
